version: '3.8'
services:
  auth-db:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_DATABASE: 'auth-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - auth-db:/var/lib/mysql
    networks:
      - microservices-network

  auth-service:
    image: "openjdk:17"
    working_dir: /app
    volumes:
      - "D:/Praca magisterska/f1_ml/auth:/app"
    ports:
      - "8081:8081"
      - "5081:5081"
    environment:
      SPRING_APPLICATION_NAME: auth-service
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    command: ["sh", "-c", "sleep 10 && mvn -T 4 clean install java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5081 -jar target/auth-0.0.1-SNAPSHOT.jar"]
    networks:
      - microservices-network
    depends_on:
      - auth-db

networks:
  microservices-network:
    external: true

volumes:
  auth-db:
